#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 5.4
# in conjunction with Tcl version 8.6
# Jan 05, 2021 07:06:20 AM +03  platform: Windows NT

import sys, re, math
from math import sqrt

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

import kcalibrator_gui_support

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = tk.Tk()
    kcalibrator_gui_support.set_Tk_var()
    top = Toplevel (root)
    kcalibrator_gui_support.init(root, top)
    top.register_validator()
    root.mainloop()

w = None
def create_Toplevel(rt, *args, **kwargs):
    '''Starting point when module is imported by another module.
       Correct form of call: 'create_Toplevel(root, *args, **kwargs)' .'''
    global w, w_win, root
    #rt = root
    root = rt
    w = tk.Toplevel (root)
    kcalibrator_gui_support.set_Tk_var()
    top = Toplevel (w)
    kcalibrator_gui_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_Toplevel():
    global w
    w.destroy()
    w = None

def validate(field):
    """
    Validation function.
    Allows to enter only floating point numbers
    """
    regex = re.compile(r"(\+|\-)?[0-9.]*$")
    result = regex.match(field)
    return (field == ""
            or (field.count('+') <= 1
                and field.count('-') <= 1
                and field.count('.') <= 1
                and result is not None
                and result.group(0) != ""))

class Toplevel:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85'
        _ana2color = '#ececec' # Closest X11 color: 'gray92'
        self.style = ttk.Style()
        if sys.platform == "win32":
            self.style.theme_use('winnative')
        self.style.configure('.',background=_bgcolor)
        self.style.configure('.',foreground=_fgcolor)
        self.style.configure('.',font="TkDefaultFont")
        self.style.map('.',background=
            [('selected', _compcolor), ('active',_ana2color)])

        # Layout constants (window 620x400)
        self.WIN_W, self.WIN_H = 620, 450
        self.PATTERN_W, self.PATTERN_H = 360, 286
        self.MACHINE_W, self.MACHINE_H = 360, 125
        self.PRINT_W, self.PRINT_H = 230, 339

        top.geometry("620x450+400+250")
        top.minsize(620, 450)
        top.maxsize(1920, 1080)
        top.resizable(1, 1)
        top.title("Kcalibrator")
        top.configure(background="#d9d9d9")
        top.configure(highlightbackground="#d9d9d9")
        top.configure(highlightcolor="black")

        self.lf_PatternConfig = tk.LabelFrame(top)
        self.lf_PatternConfig.place(x=10, y=0, width=self.PATTERN_W, height=self.PATTERN_H)
        self.lf_PatternConfig.configure(relief='groove')
        self.lf_PatternConfig.configure(font="-family {Segoe UI} -size 10 -weight bold -slant roman -underline 0 -overstrike 0")
        self.lf_PatternConfig.configure(foreground="black")
        self.lf_PatternConfig.configure(text='''Pattern configuration''')
        self.lf_PatternConfig.configure(background="#d9d9d9")
        self.lf_PatternConfig.configure(highlightbackground="#d9d9d9")
        self.lf_PatternConfig.configure(highlightcolor="black")

        self._lbl_StartStopStep = ttk.Label(self.lf_PatternConfig)
        self._lbl_StartStopStep.place(x=5, y=0, height=19, width=299)
        self._lbl_StartStopStep.configure(background="#d9d9d9")
        self._lbl_StartStopStep.configure(foreground="#000000")
        self._lbl_StartStopStep.configure(font="-family {Segoe UI} -size 10 -weight normal -slant roman -underline 0 -overstrike 0")
        self._lbl_StartStopStep.configure(relief="flat")
        self._lbl_StartStopStep.configure(anchor='w')
        self._lbl_StartStopStep.configure(justify='left')
        self._lbl_StartStopStep.configure(takefocus="0")
        self._lbl_StartStopStep.configure(text='''Start, stop and step values for K-factor calibration''')

        self.ent_StartK = ttk.Entry(self.lf_PatternConfig)
        self.ent_StartK.place(x=68, y=25, height=20, width=55)
        self.ent_StartK.configure(font="-family {Segoe UI} -size 10 -weight normal -slant roman -underline 0 -overstrike 0")
        self.ent_StartK.configure(takefocus="")
        # self.ent_StartK.configure(cursor="ibeam")
        self.ent_StartK_var = tk.StringVar()
        self.ent_StartK.configure(textvariable = self.ent_StartK_var)

        self.ent_StepK = ttk.Entry(self.lf_PatternConfig)
        self.ent_StepK.place(x=299, y=25, height=20, width=55)
        self.ent_StepK.configure(font="-family {Segoe UI} -size 10 -weight normal -slant roman -underline 0 -overstrike 0")
        self.ent_StepK.configure(takefocus="")
        # self.ent_StepK.configure(cursor="ibeam")
        self.ent_StepK_var = tk.StringVar()
        self.ent_StepK.configure(textvariable = self.ent_StepK_var)

        self._lbl_KFrom = ttk.Label(self.lf_PatternConfig)
        self._lbl_KFrom.place(x=5, y=25, height=20, width=60)
        self._lbl_KFrom.configure(background="#d9d9d9")
        self._lbl_KFrom.configure(foreground="#000000")
        self._lbl_KFrom.configure(font="-family {Segoe UI} -size 10 -weight normal -slant roman -underline 0 -overstrike 0")
        self._lbl_KFrom.configure(relief="flat")
        self._lbl_KFrom.configure(anchor='w')
        self._lbl_KFrom.configure(justify='left')
        self._lbl_KFrom.configure(takefocus="0")
        self._lbl_KFrom.configure(text='''From K =''')

        self._lbl_KTo = ttk.Label(self.lf_PatternConfig)
        self._lbl_KTo.place(x=126, y=25, height=20, width=40)
        self._lbl_KTo.configure(background="#d9d9d9")
        self._lbl_KTo.configure(foreground="#000000")
        self._lbl_KTo.configure(font="-family {Segoe UI} -size 10 -weight normal -slant roman -underline 0 -overstrike 0")
        self._lbl_KTo.configure(relief="flat")
        self._lbl_KTo.configure(anchor='w')
        self._lbl_KTo.configure(justify='left')
        self._lbl_KTo.configure(takefocus="0")
        self._lbl_KTo.configure(text='''to K =''')

        self._lbl_KBy = ttk.Label(self.lf_PatternConfig)
        self._lbl_KBy.place(x=229, y=25, height=22, width=65)
        self._lbl_KBy.configure(background="#d9d9d9")
        self._lbl_KBy.configure(foreground="#000000")
        self._lbl_KBy.configure(font="-family {Segoe UI} -size 10 -weight normal -slant roman -underline 0 -overstrike 0")
        self._lbl_KBy.configure(relief="flat")
        self._lbl_KBy.configure(anchor='w')
        self._lbl_KBy.configure(justify='left')
        self._lbl_KBy.configure(takefocus="0")
        self._lbl_KBy.configure(text='''change by''')

        self._lbl_FastSpeed = ttk.Label(self.lf_PatternConfig)
        self._lbl_FastSpeed.place(x=5, y=151, height=22, width=70)
        self._lbl_FastSpeed.configure(background="#d9d9d9")
        self._lbl_FastSpeed.configure(foreground="#000000")
        self._lbl_FastSpeed.configure(font="-family {Segoe UI} -size 10 -weight normal -slant roman -underline 0 -overstrike 0")
        self._lbl_FastSpeed.configure(relief="flat")
        self._lbl_FastSpeed.configure(anchor='w')
        self._lbl_FastSpeed.configure(justify='left')
        self._lbl_FastSpeed.configure(takefocus="0")
        self._lbl_FastSpeed.configure(text='''Fast speed''')

        self.ent_FastSpeed = ttk.Entry(self.lf_PatternConfig)
        self.ent_FastSpeed.place(x=77, y=151, height=20, width=50)
        self.ent_FastSpeed.configure(takefocus="")
        # self.ent_FastSpeed.configure(cursor="ibeam")
        self.ent_FastSpeed_var = tk.StringVar()
        self.ent_FastSpeed.configure(textvariable = self.ent_FastSpeed_var)

        self._lbl_SlowSpeed = ttk.Label(self.lf_PatternConfig)
        self._lbl_SlowSpeed.place(x=188, y=151, height=22, width=75)
        self._lbl_SlowSpeed.configure(background="#d9d9d9")
        self._lbl_SlowSpeed.configure(foreground="#000000")
        self._lbl_SlowSpeed.configure(font="-family {Segoe UI} -size 10 -weight normal -slant roman -underline 0 -overstrike 0")
        self._lbl_SlowSpeed.configure(relief="flat")
        self._lbl_SlowSpeed.configure(anchor='w')
        self._lbl_SlowSpeed.configure(justify='left')
        self._lbl_SlowSpeed.configure(takefocus="0")
        self._lbl_SlowSpeed.configure(text='''Slow speed''')

        self.ent_SlowSpeed = ttk.Entry(self.lf_PatternConfig)
        self.ent_SlowSpeed.place(x=260, y=151, height=20, width=50)
        self.ent_SlowSpeed.configure(font="-family {Segoe UI} -size 10 -weight normal -slant roman -underline 0 -overstrike 0")
        self.ent_SlowSpeed.configure(takefocus="")
        # self.ent_SlowSpeed.configure(cursor="ibeam")
        self.ent_SlowSpeed_var = tk.StringVar()
        self.ent_SlowSpeed.configure(textvariable = self.ent_SlowSpeed_var)

        self._lbl_Speeds = ttk.Label(self.lf_PatternConfig)
        self._lbl_Speeds.place(x=5, y=126, height=22, width=325)
        self._lbl_Speeds.configure(background="#d9d9d9")
        self._lbl_Speeds.configure(foreground="#000000")
        self._lbl_Speeds.configure(font="-family {Segoe UI} -size 10 -weight normal -slant roman -underline 0 -overstrike 0")
        self._lbl_Speeds.configure(relief="flat")
        self._lbl_Speeds.configure(anchor='w')
        self._lbl_Speeds.configure(justify='left')
        self._lbl_Speeds.configure(takefocus="0")
        self._lbl_Speeds.configure(text='''Speed values for pattern generation''')

        self._lbl_LayersPerK = ttk.Label(self.lf_PatternConfig)
        self._lbl_LayersPerK.place(x=5, y=50, height=22, width=305)
        self._lbl_LayersPerK.configure(background="#d9d9d9")
        self._lbl_LayersPerK.configure(foreground="#000000")
        self._lbl_LayersPerK.configure(font="-family {Segoe UI} -size 10 -weight normal -slant roman -underline 0 -overstrike 0")
        self._lbl_LayersPerK.configure(relief="flat")
        self._lbl_LayersPerK.configure(anchor='w')
        self._lbl_LayersPerK.configure(justify='left')
        self._lbl_LayersPerK.configure(takefocus="0")
        self._lbl_LayersPerK.configure(text='''Number of layers printed with any specific K-factor''')

        self.ent_StopK = ttk.Entry(self.lf_PatternConfig)
        self.ent_StopK.place(x=170, y=25, height=20, width=55)
        self.ent_StopK.configure(font="-family {Segoe UI} -size 10 -weight normal -slant roman -underline 0 -overstrike 0")
        self.ent_StopK.configure(takefocus="")
        # self.ent_StopK.configure(cursor="ibeam")
        self.ent_StopK_var = tk.StringVar()
        self.ent_StopK.configure(textvariable = self.ent_StopK_var)

        self.ent_LayersPerK = ttk.Entry(self.lf_PatternConfig)
        self.ent_LayersPerK.place(x=314, y=50, height=20, width=40)
        self.ent_LayersPerK.configure(takefocus="")
        # self.ent_LayersPerK.configure(cursor="ibeam")
        self.ent_LayersPerK_var = tk.StringVar()
        self.ent_LayersPerK.configure(textvariable = self.ent_LayersPerK_var)

        self.chk_AAdaptive = tk.Checkbutton(self.lf_PatternConfig)
        self.chk_AAdaptive.place(x=0, y=72, height=20, width=200)
        self.chk_AAdaptive.configure(activebackground="#ececec")
        self.chk_AAdaptive.configure(activeforeground="#000000")
        self.chk_AAdaptive.configure(background="#d9d9d9")
        self.chk_AAdaptive.configure(borderwidth="0")
        self.chk_AAdaptive.configure(disabledforeground="#a3a3a3")
        self.chk_AAdaptive.configure(font="-family {Segoe UI} -size 10 -weight normal -slant roman -underline 0 -overstrike 0")
        self.chk_AAdaptive.configure(foreground="#000000")
        self.chk_AAdaptive.configure(highlightbackground="#d9d9d9")
        self.chk_AAdaptive.configure(highlightcolor="black")
        self.chk_AAdaptive.configure(justify='left')
        self.chk_AAdaptive.configure(text='''Adaptive Pressure Advance''')
        self.chk_AAdaptive_var = tk.BooleanVar()
        self.chk_AAdaptive.configure(variable=self.chk_AAdaptive_var)

        self._lbl_AFrom = ttk.Label(self.lf_PatternConfig)
        self._lbl_AFrom.place(x=5, y=94, height=20, width=60)
        self._lbl_AFrom.configure(background="#d9d9d9")
        self._lbl_AFrom.configure(foreground="#000000")
        self._lbl_AFrom.configure(font="-family {Segoe UI} -size 10 -weight normal -slant roman -underline 0 -overstrike 0")
        self._lbl_AFrom.configure(text='''From A =''') 
        self.ent_StartA = ttk.Entry(self.lf_PatternConfig)
        self.ent_StartA.place(x=68, y=94, height=20, width=55)
        self.ent_StartA_var = tk.StringVar()
        self.ent_StartA.configure(textvariable=self.ent_StartA_var)
        self._lbl_ATo = ttk.Label(self.lf_PatternConfig)
        self._lbl_ATo.place(x=126, y=94, height=20, width=40)
        self._lbl_ATo.configure(background="#d9d9d9")
        self._lbl_ATo.configure(foreground="#000000")
        self._lbl_ATo.configure(font="-family {Segoe UI} -size 10 -weight normal -slant roman -underline 0 -overstrike 0")
        self._lbl_ATo.configure(text='''to A =''')
        self.ent_StopA = ttk.Entry(self.lf_PatternConfig)
        self.ent_StopA.place(x=170, y=94, height=20, width=55)
        self.ent_StopA_var = tk.StringVar()
        self.ent_StopA.configure(textvariable=self.ent_StopA_var)
        self._lbl_ABy = ttk.Label(self.lf_PatternConfig)
        self._lbl_ABy.place(x=229, y=94, height=20, width=65)
        self._lbl_ABy.configure(background="#d9d9d9")
        self._lbl_ABy.configure(foreground="#000000")
        self._lbl_ABy.configure(font="-family {Segoe UI} -size 10 -weight normal -slant roman -underline 0 -overstrike 0")
        self._lbl_ABy.configure(text='''change by''')
        self.ent_StepA = ttk.Entry(self.lf_PatternConfig)
        self.ent_StepA.place(x=299, y=94, height=20, width=55)
        self.ent_StepA_var = tk.StringVar()
        self.ent_StepA.configure(textvariable=self.ent_StepA_var)

        self.ent_SpdFr1 = ttk.Entry(self.lf_PatternConfig)
        self.ent_SpdFr1.place(x=172, y=176, height=20, width=50)
        self.ent_SpdFr1.configure(takefocus="")
        # self.ent_SpdFr1.configure(cursor="ibeam")
        self.ent_SpdFr1_var = tk.StringVar()
        self.ent_SpdFr1.configure(textvariable = self.ent_SpdFr1_var)

        self.ent_SpdFr2 = ttk.Entry(self.lf_PatternConfig)
        self.ent_SpdFr2.place(x=238, y=176, height=20, width=50)
        self.ent_SpdFr2.configure(takefocus="")
        # self.ent_SpdFr2.configure(cursor="ibeam")
        self.ent_SpdFr2_var = tk.StringVar()
        self.ent_SpdFr2.configure(textvariable = self.ent_SpdFr2_var)

        self.ent_SpdFr3 = ttk.Entry(self.lf_PatternConfig)
        self.ent_SpdFr3.place(x=304, y=176, height=20, width=50)
        self.ent_SpdFr3.configure(takefocus="")
        # self.ent_SpdFr3.configure(cursor="ibeam")
        self.ent_SpdFr3_var = tk.StringVar()
        self.ent_SpdFr3.configure(textvariable = self.ent_SpdFr3_var)

        self._lbl_SpeedFractions = ttk.Label(self.lf_PatternConfig)
        self._lbl_SpeedFractions.place(x=5, y=176, height=22, width=160)
        self._lbl_SpeedFractions.configure(background="#d9d9d9")
        self._lbl_SpeedFractions.configure(foreground="#000000")
        self._lbl_SpeedFractions.configure(font="-family {Segoe UI} -size 10 -weight normal -slant roman -underline 0 -overstrike 0")
        self._lbl_SpeedFractions.configure(relief="flat")
        self._lbl_SpeedFractions.configure(anchor='w')
        self._lbl_SpeedFractions.configure(justify='left')
        self._lbl_SpeedFractions.configure(takefocus="0")
        self._lbl_SpeedFractions.configure(text='''Fractions for pattern paths''')

        self._lbl_PatternSize = ttk.Label(self.lf_PatternConfig)
        self._lbl_PatternSize.place(x=5, y=211, height=22, width=160)
        self._lbl_PatternSize.configure(background="#d9d9d9")
        self._lbl_PatternSize.configure(foreground="#000000")
        self._lbl_PatternSize.configure(font="-family {Segoe UI} -size 10 -weight normal -slant roman -underline 0 -overstrike 0")
        self._lbl_PatternSize.configure(relief="flat")
        self._lbl_PatternSize.configure(anchor='w')
        self._lbl_PatternSize.configure(justify='left')
        self._lbl_PatternSize.configure(takefocus="0")
        self._lbl_PatternSize.configure(text='''Size of the pattern (XxYxZ):''')

        self._lbl_psx = ttk.Label(self.lf_PatternConfig)
        self._lbl_psx.place(x=219, y=211, height=22, width=10)
        self._lbl_psx.configure(background="#d9d9d9")
        self._lbl_psx.configure(foreground="#000000")
        self._lbl_psx.configure(font="-family {Segoe UI} -size 10 -weight normal -slant roman -underline 0 -overstrike 0")
        self._lbl_psx.configure(relief="flat")
        self._lbl_psx.configure(anchor='w')
        self._lbl_psx.configure(justify='left')
        self._lbl_psx.configure(takefocus="0")
        self._lbl_psx.configure(text='''x''')

        self.ent_PatternXsize = ttk.Entry(self.lf_PatternConfig)
        self.ent_PatternXsize.place(x=167, y=211, height=20, width=50)
        self.ent_PatternXsize.configure(takefocus="")
        # self.ent_PatternXsize.configure(cursor="ibeam")
        self.ent_PatternXsize_var = tk.StringVar()
        self.ent_PatternXsize.configure(textvariable = self.ent_PatternXsize_var)

        self.ent_PatternYsize = ttk.Entry(self.lf_PatternConfig)
        self.ent_PatternYsize.place(x=231, y=211, height=20, width=50)
        self.ent_PatternYsize.configure(takefocus="")
        # self.ent_PatternYsize.configure(cursor="ibeam")
        self.ent_PatternYsize_var = tk.StringVar()
        self.ent_PatternYsize.configure(textvariable = self.ent_PatternYsize_var)

        self.lbl_PatternZsize = ttk.Label(self.lf_PatternConfig)
        self.lbl_PatternZsize.place(x=284, y=211, height=22, width=70)
        self.lbl_PatternZsize.configure(background="#d9d9d9")
        self.lbl_PatternZsize.configure(foreground="#000000")
        self.lbl_PatternZsize.configure(font="-family {Segoe UI} -size 10 -weight normal -slant roman -underline 0 -overstrike 0")
        self.lbl_PatternZsize.configure(relief="flat")
        self.lbl_PatternZsize.configure(anchor='w')
        self.lbl_PatternZsize.configure(justify='left')
        self.lbl_PatternZsize.configure(takefocus="0")
        self.lbl_PatternZsize.configure(text='''x 100 mm''')

        self.chk_TwoPerimeters = tk.Checkbutton(self.lf_PatternConfig)
        self.chk_TwoPerimeters.place(x=5, y=236, height=22, width=300)
        self.chk_TwoPerimeters.configure(activebackground="#ececec")
        self.chk_TwoPerimeters.configure(activeforeground="#000000")
        self.chk_TwoPerimeters.configure(background="#d9d9d9")
        self.chk_TwoPerimeters.configure(borderwidth="0")
        self.chk_TwoPerimeters.configure(disabledforeground="#a3a3a3")
        self.chk_TwoPerimeters.configure(font="-family {Segoe UI} -size 10 -weight normal -slant roman -underline 0 -overstrike 0")
        self.chk_TwoPerimeters.configure(foreground="#000000")
        self.chk_TwoPerimeters.configure(highlightbackground="#d9d9d9")
        self.chk_TwoPerimeters.configure(highlightcolor="black")
        self.chk_TwoPerimeters.configure(justify='left')
        self.chk_TwoPerimeters.configure(text='''Print pattern with two perimeters instead of one''')
        self.chk_TwoPerimeters_var = tk.BooleanVar()
        self.chk_TwoPerimeters.configure(variable=self.chk_TwoPerimeters_var)

        self._lbl_unitsFastSpeed = ttk.Label(self.lf_PatternConfig)
        self._lbl_unitsFastSpeed.place(x=130, y=151, height=22, width=40)
        self._lbl_unitsFastSpeed.configure(background="#d9d9d9")
        self._lbl_unitsFastSpeed.configure(foreground="#000000")
        self._lbl_unitsFastSpeed.configure(font="-family {Segoe UI} -size 10 -weight normal -slant roman -underline 0 -overstrike 0")
        self._lbl_unitsFastSpeed.configure(relief="flat")
        self._lbl_unitsFastSpeed.configure(anchor='w')
        self._lbl_unitsFastSpeed.configure(justify='left')
        self._lbl_unitsFastSpeed.configure(takefocus="0")
        self._lbl_unitsFastSpeed.configure(text='''mm/s''')

        self._lbl_unitsSlowSpeed = ttk.Label(self.lf_PatternConfig)
        self._lbl_unitsSlowSpeed.place(x=310, y=151, height=22, width=40)
        self._lbl_unitsSlowSpeed.configure(background="#d9d9d9")
        self._lbl_unitsSlowSpeed.configure(foreground="#000000")
        self._lbl_unitsSlowSpeed.configure(font="-family {Segoe UI} -size 10 -weight normal -slant roman -underline 0 -overstrike 0")
        self._lbl_unitsSlowSpeed.configure(relief="flat")
        self._lbl_unitsSlowSpeed.configure(anchor='w')
        self._lbl_unitsSlowSpeed.configure(justify='left')
        self._lbl_unitsSlowSpeed.configure(takefocus="0")
        self._lbl_unitsSlowSpeed.configure(text='''mm/s''')

        self.TSeparator1 = ttk.Separator(self.lf_PatternConfig)
        self.TSeparator1.place(x=0, y=120, width=self.PATTERN_W+4, height=2)

        self.TSeparator2 = ttk.Separator(self.lf_PatternConfig)
        self.TSeparator2.place(x=0, y=203, width=self.PATTERN_W+4, height=2)

        self.lf_MachineConfig = tk.LabelFrame(top)
        self.lf_MachineConfig.place(x=10, y=290, width=self.MACHINE_W, height=self.MACHINE_H)
        self.lf_MachineConfig.configure(relief='groove')
        self.lf_MachineConfig.configure(font="-family {Segoe UI} -size 10 -weight bold -slant roman -underline 0 -overstrike 0")
        self.lf_MachineConfig.configure(foreground="black")
        self.lf_MachineConfig.configure(text='''Machine configuration''')
        self.lf_MachineConfig.configure(background="#d9d9d9")
        self.lf_MachineConfig.configure(highlightbackground="#d9d9d9")
        self.lf_MachineConfig.configure(highlightcolor="black")

        self._lbl_Kinematics = ttk.Label(self.lf_MachineConfig)
        self._lbl_Kinematics.place(x=5, y=5, height=22, width=70)
        self._lbl_Kinematics.configure(background="#d9d9d9")
        self._lbl_Kinematics.configure(foreground="#000000")
        self._lbl_Kinematics.configure(font="-family {Segoe UI} -size 10 -weight normal -slant roman -underline 0 -overstrike 0")
        self._lbl_Kinematics.configure(relief="flat")
        self._lbl_Kinematics.configure(anchor='w')
        self._lbl_Kinematics.configure(justify='left')
        self._lbl_Kinematics.configure(takefocus="0")
        self._lbl_Kinematics.configure(text='''Kinematics''')

        self.cmb_Kinematics = ttk.Combobox(self.lf_MachineConfig, state = ("readonly",))
        self.cmb_Kinematics.place(x=75, y=5, height=25, width=103)
        # self.cmb_Kinematics_value_list = ['Cartesian','Delta',]
        # self.cmb_Kinematics.configure(values=self.cmb_Kinematics_value_list)
        self.cmb_Kinematics.configure(font="-family {Segoe UI} -size 10 -weight normal -slant roman -underline 0 -overstrike 0")
        self.cmb_Kinematics.configure(takefocus="")
        self.cmb_Kinematics_var = tk.StringVar()
        self.cmb_Kinematics.configure(textvariable = self.cmb_Kinematics_var)

        self._lbl_Firmware = ttk.Label(self.lf_MachineConfig)
        self._lbl_Firmware.place(x=190, y=5, height=22, width=60)
        self._lbl_Firmware.configure(background="#d9d9d9")
        self._lbl_Firmware.configure(foreground="#000000")
        self._lbl_Firmware.configure(font="-family {Segoe UI} -size 10 -weight normal -slant roman -underline 0 -overstrike 0")
        self._lbl_Firmware.configure(relief="flat")
        self._lbl_Firmware.configure(anchor='w')
        self._lbl_Firmware.configure(justify='left')
        self._lbl_Firmware.configure(takefocus="0")
        self._lbl_Firmware.configure(text='''Firmware''')

        self.cmb_Firmware = ttk.Combobox(self.lf_MachineConfig, state = ("readonly",))
        self.cmb_Firmware.place(x=250, y=5, height=25, width=103)
        # self.cmb_Firmware_value_list = ['Marlin/Lerdge','Klipper','RepRapFirmware',]
        # self.cmb_Firmware.configure(values=self.cmb_Firmware_value_list)
        self.cmb_Firmware.configure(font="-family {Segoe UI} -size 10 -weight normal -slant roman -underline 0 -overstrike 0")
        self.cmb_Firmware.configure(takefocus="")
        self.cmb_Firmware_var = tk.StringVar()
        self.cmb_Firmware.configure(textvariable = self.cmb_Firmware_var)

        self._lbl_BuildVol = ttk.Label(self.lf_MachineConfig)
        self._lbl_BuildVol.place(x=5, y=40, height=22, width=90)
        self._lbl_BuildVol.configure(background="#d9d9d9")
        self._lbl_BuildVol.configure(foreground="#000000")
        self._lbl_BuildVol.configure(font="-family {Segoe UI} -size 10 -weight normal -slant roman -underline 0 -overstrike 0")
        self._lbl_BuildVol.configure(relief="flat")
        self._lbl_BuildVol.configure(anchor='w')
        self._lbl_BuildVol.configure(justify='left')
        self._lbl_BuildVol.configure(takefocus="0")
        self._lbl_BuildVol.configure(text='''Build volume:''')

        self.ent_BuildVolY = ttk.Entry(self.lf_MachineConfig)
        self.ent_BuildVolY.place(x=160, y=40, height=20, width=55)
        self.ent_BuildVolY.configure(takefocus="")
        # self.ent_BuildVolY.configure(cursor="ibeam")
        self.ent_BuildVolY_var = tk.StringVar()
        self.ent_BuildVolY.configure(textvariable = self.ent_BuildVolY_var)

        self.ent_BuildVolX = ttk.Entry(self.lf_MachineConfig)
        self.ent_BuildVolX.place(x=90, y=40, height=20, width=55)
        self.ent_BuildVolX.configure(takefocus="")
        # self.ent_BuildVolX.configure(cursor="ibeam")
        self.ent_BuildVolX_var = tk.StringVar()
        self.ent_BuildVolX.configure(textvariable = self.ent_BuildVolX_var)

        self._lbl_bvx1 = ttk.Label(self.lf_MachineConfig)
        self._lbl_bvx1.place(x=147, y=40, height=22, width=10)
        self._lbl_bvx1.configure(background="#d9d9d9")
        self._lbl_bvx1.configure(foreground="#000000")
        self._lbl_bvx1.configure(font="-family {Segoe UI} -size 10 -weight normal -slant roman -underline 0 -overstrike 0")
        self._lbl_bvx1.configure(relief="flat")
        self._lbl_bvx1.configure(anchor='w')
        self._lbl_bvx1.configure(justify='left')
        self._lbl_bvx1.configure(takefocus="0")
        self._lbl_bvx1.configure(text='''x''')

        self.lbl_bvx2_units = ttk.Label(self.lf_MachineConfig)
        self.lbl_bvx2_units.place(x=217, y=35, height=30, width=120)
        self.lbl_bvx2_units.configure(background="#d9d9d9")
        self.lbl_bvx2_units.configure(foreground="#000000")
        self.lbl_bvx2_units.configure(font="-family {Segoe UI} -size 10 -weight normal -slant roman -underline 0 -overstrike 0")
        self.lbl_bvx2_units.configure(relief="flat")
        self.lbl_bvx2_units.configure(anchor='w')
        self.lbl_bvx2_units.configure(justify='left')
        self.lbl_bvx2_units.configure(takefocus="0")
        self.lbl_bvx2_units.configure(text='''x''')

        self.lbl_bvx3_units = ttk.Label(self.lf_MachineConfig)
        self.lbl_bvx3_units.place(x=290, y=40, height=22, width=30)
        self.lbl_bvx3_units.configure(background="#d9d9d9")
        self.lbl_bvx3_units.configure(foreground="#000000")
        self.lbl_bvx3_units.configure(font="-family {Segoe UI} -size 10 -weight normal -slant roman -underline 0 -overstrike 0")
        self.lbl_bvx3_units.configure(relief="flat")
        self.lbl_bvx3_units.configure(anchor='w')
        self.lbl_bvx3_units.configure(justify='left')
        self.lbl_bvx3_units.configure(takefocus="0")
        self.lbl_bvx3_units.configure(text='''mm''')

        self.cmb_AutolevelingType = ttk.Combobox(self.lf_MachineConfig, state = ("readonly",))
        self.cmb_AutolevelingType.place(x=280, y=70, height=25, width=73)
        # self.cmb_AutolevelingType_value_list = ['G29','M83',]
        # self.cmb_AutolevelingType.configure(values=self.cmb_AutolevelingType_value_list)
        self.cmb_AutolevelingType.configure(font="-family {Segoe UI} -size 10 -weight normal -slant roman -underline 0 -overstrike 0")
        self.cmb_AutolevelingType.configure(takefocus="")
        self.cmb_AutolevelingType_var = tk.StringVar()
        self.cmb_AutolevelingType.configure(textvariable = self.cmb_AutolevelingType_var)


        self._lbl_AutolevelingType = ttk.Label(self.lf_MachineConfig)
        self._lbl_AutolevelingType.place(x=170, y=70, height=22, width=105)
        self._lbl_AutolevelingType.configure(background="#d9d9d9")
        self._lbl_AutolevelingType.configure(foreground="#000000")
        self._lbl_AutolevelingType.configure(font="-family {Segoe UI} -size 10 -weight normal -slant roman -underline 0 -overstrike 0")
        self._lbl_AutolevelingType.configure(relief="flat")
        self._lbl_AutolevelingType.configure(anchor='w')
        self._lbl_AutolevelingType.configure(justify='left')
        self._lbl_AutolevelingType.configure(takefocus="0")
        self._lbl_AutolevelingType.configure(text='''Autoleveling type''')

        self.chk_UseAutoleveling = tk.Checkbutton(self.lf_MachineConfig)
        self.chk_UseAutoleveling.place(x=5, y=70, height=22, width=120)
        self.chk_UseAutoleveling.configure(activebackground="#ececec")
        self.chk_UseAutoleveling.configure(activeforeground="#000000")
        self.chk_UseAutoleveling.configure(background="#d9d9d9")
        self.chk_UseAutoleveling.configure(borderwidth="0")
        self.chk_UseAutoleveling.configure(disabledforeground="#a3a3a3")
        self.chk_UseAutoleveling.configure(font="-family {Segoe UI} -size 10 -weight normal -slant roman -underline 0 -overstrike 0")
        self.chk_UseAutoleveling.configure(foreground="#000000")
        self.chk_UseAutoleveling.configure(highlightbackground="#d9d9d9")
        self.chk_UseAutoleveling.configure(highlightcolor="black")
        self.chk_UseAutoleveling.configure(justify='left')
        self.chk_UseAutoleveling.configure(text='''Use autoleveling''')
        self.chk_UseAutoleveling_var = tk.BooleanVar()
        self.chk_UseAutoleveling.configure(variable=self.chk_UseAutoleveling_var)

        self.ent_BuildVolZ = ttk.Entry(self.lf_MachineConfig)
        self.ent_BuildVolZ.place(x=229, y=40, height=20, width=55)
        self.ent_BuildVolZ.configure(takefocus="")
        # self.ent_BuildVolZ.configure(cursor="ibeam")
        self.ent_BuildVolZ_var = tk.StringVar()
        self.ent_BuildVolZ.configure(textvariable = self.ent_BuildVolZ_var)

        self.lf_PrintConfig = tk.LabelFrame(top)
        self.lf_PrintConfig.place(x=380, y=0, width=self.PRINT_W, height=self.PRINT_H)
        self.lf_PrintConfig.configure(relief='groove')
        self.lf_PrintConfig.configure(font="-family {Segoe UI} -size 10 -weight bold -slant roman -underline 0 -overstrike 0")
        self.lf_PrintConfig.configure(foreground="black")
        self.lf_PrintConfig.configure(text='''Print configuration''')
        self.lf_PrintConfig.configure(background="#d9d9d9")
        self.lf_PrintConfig.configure(highlightbackground="#d9d9d9")
        self.lf_PrintConfig.configure(highlightcolor="black")

        self._lbl_NozzleTemp = ttk.Label(self.lf_PrintConfig)
        self._lbl_NozzleTemp.place(x=5, y=0, height=22, width=120)
        self._lbl_NozzleTemp.configure(background="#d9d9d9")
        self._lbl_NozzleTemp.configure(foreground="#000000")
        self._lbl_NozzleTemp.configure(font="-family {Segoe UI} -size 10 -weight normal -slant roman -underline 0 -overstrike 0")
        self._lbl_NozzleTemp.configure(relief="flat")
        self._lbl_NozzleTemp.configure(anchor='w')
        self._lbl_NozzleTemp.configure(justify='left')
        self._lbl_NozzleTemp.configure(takefocus="0")
        self._lbl_NozzleTemp.configure(text='''Nozzle temperature''')

        self._lbl_BedTemp = ttk.Label(self.lf_PrintConfig)
        self._lbl_BedTemp.place(x=5, y=25, height=22, width=105)
        self._lbl_BedTemp.configure(background="#d9d9d9")
        self._lbl_BedTemp.configure(foreground="#000000")
        self._lbl_BedTemp.configure(font="-family {Segoe UI} -size 10 -weight normal -slant roman -underline 0 -overstrike 0")
        self._lbl_BedTemp.configure(relief="flat")
        self._lbl_BedTemp.configure(anchor='w')
        self._lbl_BedTemp.configure(justify='left')
        self._lbl_BedTemp.configure(takefocus="0")
        self._lbl_BedTemp.configure(text='''Bed temperature''')

        self.ent_NozzleTemp = ttk.Entry(self.lf_PrintConfig)
        self.ent_NozzleTemp.place(x=130, y=0, height=20, width=55)
        self.ent_NozzleTemp.configure(takefocus="")
        # self.ent_NozzleTemp.configure(cursor="ibeam")
        self.ent_NozzleTemp_var = tk.StringVar()
        self.ent_NozzleTemp.configure(textvariable = self.ent_NozzleTemp_var)

        self.ent_BedTemp = ttk.Entry(self.lf_PrintConfig)
        self.ent_BedTemp.place(x=130, y=25, height=20, width=55)
        self.ent_BedTemp.configure(takefocus="")
        # self.ent_BedTemp.configure(cursor="ibeam")
        self.ent_BedTemp_var = tk.StringVar()
        self.ent_BedTemp.configure(textvariable = self.ent_BedTemp_var)

        self.chk_RetractAtLayerChange = tk.Checkbutton(self.lf_PrintConfig)
        self.chk_RetractAtLayerChange.place(x=5, y=130, height=22, width=155)
        self.chk_RetractAtLayerChange.configure(activebackground="#ececec")
        self.chk_RetractAtLayerChange.configure(activeforeground="#000000")
        self.chk_RetractAtLayerChange.configure(background="#d9d9d9")
        self.chk_RetractAtLayerChange.configure(borderwidth="0")
        self.chk_RetractAtLayerChange.configure(disabledforeground="#a3a3a3")
        self.chk_RetractAtLayerChange.configure(font="-family {Segoe UI} -size 10 -weight normal -slant roman -underline 0 -overstrike 0")
        self.chk_RetractAtLayerChange.configure(foreground="#000000")
        self.chk_RetractAtLayerChange.configure(highlightbackground="#d9d9d9")
        self.chk_RetractAtLayerChange.configure(highlightcolor="black")
        self.chk_RetractAtLayerChange.configure(justify='left')
        self.chk_RetractAtLayerChange.configure(text='''Retract at layer change''')
        self.chk_RetractAtLayerChange_var = tk.BooleanVar()
        self.chk_RetractAtLayerChange.configure(variable=self.chk_RetractAtLayerChange_var)

        self._lbl_RetractSpeed = ttk.Label(self.lf_PrintConfig)
        self._lbl_RetractSpeed.place(x=5, y=105, height=22, width=120)
        self._lbl_RetractSpeed.configure(background="#d9d9d9")
        self._lbl_RetractSpeed.configure(foreground="#000000")
        self._lbl_RetractSpeed.configure(font="-family {Segoe UI} -size 10 -weight normal -slant roman -underline 0 -overstrike 0")
        self._lbl_RetractSpeed.configure(relief="flat")
        self._lbl_RetractSpeed.configure(anchor='w')
        self._lbl_RetractSpeed.configure(justify='left')
        self._lbl_RetractSpeed.configure(takefocus="0")
        self._lbl_RetractSpeed.configure(text='''Retraction speed''')

        self._lbl_RetractDist = ttk.Label(self.lf_PrintConfig)
        self._lbl_RetractDist.place(x=5, y=80, height=22, width=120)
        self._lbl_RetractDist.configure(background="#d9d9d9")
        self._lbl_RetractDist.configure(foreground="#000000")
        self._lbl_RetractDist.configure(font="-family {Segoe UI} -size 10 -weight normal -slant roman -underline 0 -overstrike 0")
        self._lbl_RetractDist.configure(relief="flat")
        self._lbl_RetractDist.configure(anchor='w')
        self._lbl_RetractDist.configure(justify='left')
        self._lbl_RetractDist.configure(takefocus="0")
        self._lbl_RetractDist.configure(text='''Retraction distance''')

        self.ent_RetractDist = ttk.Entry(self.lf_PrintConfig)
        self.ent_RetractDist.place(x=130, y=80, height=20, width=55)
        self.ent_RetractDist.configure(takefocus="")
        # self.ent_RetractDist.configure(cursor="ibeam")
        self.ent_RetractDist_var = tk.StringVar()
        self.ent_RetractDist.configure(textvariable = self.ent_RetractDist_var)

        self.ent_RetractSpeed = ttk.Entry(self.lf_PrintConfig)
        self.ent_RetractSpeed.place(x=130, y=105, height=20, width=55)
        self.ent_RetractSpeed.configure(takefocus="")
        # self.ent_RetractSpeed.configure(cursor="ibeam")
        self.ent_RetractSpeed_var = tk.StringVar()
        self.ent_RetractSpeed.configure(textvariable = self.ent_RetractSpeed_var)

        self._lbl_unitsRetractDist = ttk.Label(self.lf_PrintConfig)
        self._lbl_unitsRetractDist.place(x=185, y=80, height=22, width=30)
        self._lbl_unitsRetractDist.configure(background="#d9d9d9")
        self._lbl_unitsRetractDist.configure(foreground="#000000")
        self._lbl_unitsRetractDist.configure(font="-family {Segoe UI} -size 10 -weight normal -slant roman -underline 0 -overstrike 0")
        self._lbl_unitsRetractDist.configure(relief="flat")
        self._lbl_unitsRetractDist.configure(anchor='w')
        self._lbl_unitsRetractDist.configure(justify='left')
        self._lbl_unitsRetractDist.configure(takefocus="0")
        self._lbl_unitsRetractDist.configure(text='''mm''')

        self._lbl_unitsRetractSpeed = ttk.Label(self.lf_PrintConfig)
        self._lbl_unitsRetractSpeed.place(x=185, y=105, height=22, width=40)
        self._lbl_unitsRetractSpeed.configure(background="#d9d9d9")
        self._lbl_unitsRetractSpeed.configure(foreground="#000000")
        self._lbl_unitsRetractSpeed.configure(font="-family {Segoe UI} -size 10 -weight normal -slant roman -underline 0 -overstrike 0")
        self._lbl_unitsRetractSpeed.configure(relief="flat")
        self._lbl_unitsRetractSpeed.configure(anchor='w')
        self._lbl_unitsRetractSpeed.configure(justify='left')
        self._lbl_unitsRetractSpeed.configure(takefocus="0")
        self._lbl_unitsRetractSpeed.configure(text='''mm/s''')

        self._lbl_unitsNozzleTemp = ttk.Label(self.lf_PrintConfig)
        self._lbl_unitsNozzleTemp.place(x=185, y=0, height=22, width=20)
        self._lbl_unitsNozzleTemp.configure(background="#d9d9d9")
        self._lbl_unitsNozzleTemp.configure(foreground="#000000")
        self._lbl_unitsNozzleTemp.configure(font="-family {Segoe UI} -size 10 -weight normal -slant roman -underline 0 -overstrike 0")
        self._lbl_unitsNozzleTemp.configure(relief="flat")
        self._lbl_unitsNozzleTemp.configure(anchor='w')
        self._lbl_unitsNozzleTemp.configure(justify='left')
        self._lbl_unitsNozzleTemp.configure(takefocus="0")
        self._lbl_unitsNozzleTemp.configure(text='''°C''')

        self._lbl_unitsBedTemp = ttk.Label(self.lf_PrintConfig)
        self._lbl_unitsBedTemp.place(x=185, y=25, height=22, width=20)
        self._lbl_unitsBedTemp.configure(background="#d9d9d9")
        self._lbl_unitsBedTemp.configure(foreground="#000000")
        self._lbl_unitsBedTemp.configure(font="-family {Segoe UI} -size 10 -weight normal -slant roman -underline 0 -overstrike 0")
        self._lbl_unitsBedTemp.configure(relief="flat")
        self._lbl_unitsBedTemp.configure(anchor='w')
        self._lbl_unitsBedTemp.configure(justify='left')
        self._lbl_unitsBedTemp.configure(takefocus="0")
        self._lbl_unitsBedTemp.configure(text='''°C''')

        self._lbl_Cooling = ttk.Label(self.lf_PrintConfig)
        self._lbl_Cooling.place(x=5, y=50, height=22, width=50)
        self._lbl_Cooling.configure(background="#d9d9d9")
        self._lbl_Cooling.configure(foreground="#000000")
        self._lbl_Cooling.configure(font="-family {Segoe UI} -size 10 -weight normal -slant roman -underline 0 -overstrike 0")
        self._lbl_Cooling.configure(relief="flat")
        self._lbl_Cooling.configure(anchor='w')
        self._lbl_Cooling.configure(justify='left')
        self._lbl_Cooling.configure(takefocus="0")
        self._lbl_Cooling.configure(text='''Cooling''')

        self.lbl_CoolingPerc = ttk.Label(self.lf_PrintConfig)
        self.lbl_CoolingPerc.place(x=185, y=50, height=22, width=40)
        self.lbl_CoolingPerc.configure(background="#d9d9d9")
        self.lbl_CoolingPerc.configure(foreground="#000000")
        self.lbl_CoolingPerc.configure(font="-family {Segoe UI} -size 10 -weight normal -slant roman -underline 0 -overstrike 0")
        self.lbl_CoolingPerc.configure(relief="flat")
        self.lbl_CoolingPerc.configure(anchor='w')
        self.lbl_CoolingPerc.configure(justify='left')
        self.lbl_CoolingPerc.configure(takefocus="0")
        self.lbl_CoolingPerc.configure(text='''50%''')

        self.TSeparator3 = ttk.Separator(self.lf_PrintConfig)
        self.TSeparator3.place(x=0, y=75, width=self.PRINT_W+4, height=2)

        self.TSeparator4 = ttk.Separator(self.lf_PrintConfig)
        self.TSeparator4.place(x=0, y=157, width=self.PRINT_W+4, height=2)

        self._lbl_FirstLayerSpeed = ttk.Label(self.lf_PrintConfig)
        self._lbl_FirstLayerSpeed.place(x=5, y=165, height=22, width=120)
        self._lbl_FirstLayerSpeed.configure(background="#d9d9d9")
        self._lbl_FirstLayerSpeed.configure(foreground="#000000")
        self._lbl_FirstLayerSpeed.configure(font="-family {Segoe UI} -size 10 -weight normal -slant roman -underline 0 -overstrike 0")
        self._lbl_FirstLayerSpeed.configure(relief="flat")
        self._lbl_FirstLayerSpeed.configure(anchor='w')
        self._lbl_FirstLayerSpeed.configure(justify='left')
        self._lbl_FirstLayerSpeed.configure(takefocus="0")
        self._lbl_FirstLayerSpeed.configure(text='''First layer speed''')

        self._lbl_TravelSpeed = ttk.Label(self.lf_PrintConfig)
        self._lbl_TravelSpeed.place(x=5, y=190, height=22, width=120)
        self._lbl_TravelSpeed.configure(background="#d9d9d9")
        self._lbl_TravelSpeed.configure(foreground="#000000")
        self._lbl_TravelSpeed.configure(font="-family {Segoe UI} -size 10 -weight normal -slant roman -underline 0 -overstrike 0")
        self._lbl_TravelSpeed.configure(relief="flat")
        self._lbl_TravelSpeed.configure(anchor='w')
        self._lbl_TravelSpeed.configure(justify='left')
        self._lbl_TravelSpeed.configure(takefocus="0")
        self._lbl_TravelSpeed.configure(text='''Travel speed''')

        self._lbl_LineWidth = ttk.Label(self.lf_PrintConfig)
        self._lbl_LineWidth.place(x=5, y=220, height=22, width=120)
        self._lbl_LineWidth.configure(background="#d9d9d9")
        self._lbl_LineWidth.configure(foreground="#000000")
        self._lbl_LineWidth.configure(font="-family {Segoe UI} -size 10 -weight normal -slant roman -underline 0 -overstrike 0")
        self._lbl_LineWidth.configure(relief="flat")
        self._lbl_LineWidth.configure(anchor='w')
        self._lbl_LineWidth.configure(justify='left')
        self._lbl_LineWidth.configure(takefocus="0")
        self._lbl_LineWidth.configure(text='''Line width''')

        self._lbl_LayerHeight = ttk.Label(self.lf_PrintConfig)
        self._lbl_LayerHeight.place(x=5, y=245, height=22, width=120)
        self._lbl_LayerHeight.configure(background="#d9d9d9")
        self._lbl_LayerHeight.configure(foreground="#000000")
        self._lbl_LayerHeight.configure(font="-family {Segoe UI} -size 10 -weight normal -slant roman -underline 0 -overstrike 0")
        self._lbl_LayerHeight.configure(relief="flat")
        self._lbl_LayerHeight.configure(anchor='w')
        self._lbl_LayerHeight.configure(justify='left')
        self._lbl_LayerHeight.configure(takefocus="0")
        self._lbl_LayerHeight.configure(text='''Layer height''')

        self._lbl_FilamentDia = ttk.Label(self.lf_PrintConfig)
        self._lbl_FilamentDia.place(x=5, y=270, height=22, width=120)
        self._lbl_FilamentDia.configure(background="#d9d9d9")
        self._lbl_FilamentDia.configure(foreground="#000000")
        self._lbl_FilamentDia.configure(font="-family {Segoe UI} -size 10 -weight normal -slant roman -underline 0 -overstrike 0")
        self._lbl_FilamentDia.configure(relief="flat")
        self._lbl_FilamentDia.configure(anchor='w')
        self._lbl_FilamentDia.configure(justify='left')
        self._lbl_FilamentDia.configure(takefocus="0")
        self._lbl_FilamentDia.configure(text='''Filament diameter''')

        self.ent_FirstLayerSpeed = ttk.Entry(self.lf_PrintConfig)
        self.ent_FirstLayerSpeed.place(x=130, y=165, height=20, width=55)
        self.ent_FirstLayerSpeed.configure(takefocus="")
        # self.ent_FirstLayerSpeed.configure(cursor="ibeam")
        self.ent_FirstLayerSpeed_var = tk.StringVar()
        self.ent_FirstLayerSpeed.configure(textvariable = self.ent_FirstLayerSpeed_var)

        self.ent_TravelSpeed = ttk.Entry(self.lf_PrintConfig)
        self.ent_TravelSpeed.place(x=130, y=190, height=20, width=55)
        self.ent_TravelSpeed.configure(takefocus="")
        # self.ent_TravelSpeed.configure(cursor="ibeam")
        self.ent_TravelSpeed_var = tk.StringVar()
        self.ent_TravelSpeed.configure(textvariable = self.ent_TravelSpeed_var)

        self.TSeparator5 = ttk.Separator(self.lf_PrintConfig)
        self.TSeparator5.place(x=0, y=215, width=self.PRINT_W+4, height=2)

        self.ent_LineWidth = ttk.Entry(self.lf_PrintConfig)
        self.ent_LineWidth.place(x=130, y=220, height=20, width=55)
        self.ent_LineWidth.configure(takefocus="")
        # self.ent_LineWidth.configure(cursor="ibeam")
        self.ent_LineWidth_var = tk.StringVar()
        self.ent_LineWidth.configure(textvariable = self.ent_LineWidth_var)

        self.ent_LayerHeight = ttk.Entry(self.lf_PrintConfig)
        self.ent_LayerHeight.place(x=130, y=245, height=20, width=55)
        self.ent_LayerHeight.configure(takefocus="")
        # self.ent_LayerHeight.configure(cursor="ibeam")
        self.ent_LayerHeight_var = tk.StringVar()
        self.ent_LayerHeight.configure(textvariable = self.ent_LayerHeight_var)

        self.ent_FilamentDia = ttk.Entry(self.lf_PrintConfig)
        self.ent_FilamentDia.place(x=130, y=270, height=20, width=55)
        self.ent_FilamentDia.configure(takefocus="")
        # self.ent_FilamentDia.configure(cursor="ibeam")
        self.ent_FilamentDia_var = tk.StringVar()
        self.ent_FilamentDia.configure(textvariable = self.ent_FilamentDia_var)

        self._lbl_unitsLineWidth = ttk.Label(self.lf_PrintConfig)
        self._lbl_unitsLineWidth.place(x=185, y=220, height=22, width=30)
        self._lbl_unitsLineWidth.configure(background="#d9d9d9")
        self._lbl_unitsLineWidth.configure(foreground="#000000")
        self._lbl_unitsLineWidth.configure(font="-family {Segoe UI} -size 10 -weight normal -slant roman -underline 0 -overstrike 0")
        self._lbl_unitsLineWidth.configure(relief="flat")
        self._lbl_unitsLineWidth.configure(anchor='w')
        self._lbl_unitsLineWidth.configure(justify='left')
        self._lbl_unitsLineWidth.configure(takefocus="0")
        self._lbl_unitsLineWidth.configure(text='''mm''')

        self._lbl_unitsLayerHeight = ttk.Label(self.lf_PrintConfig)
        self._lbl_unitsLayerHeight.place(x=185, y=245, height=22, width=30)
        self._lbl_unitsLayerHeight.configure(background="#d9d9d9")
        self._lbl_unitsLayerHeight.configure(foreground="#000000")
        self._lbl_unitsLayerHeight.configure(font="-family {Segoe UI} -size 10 -weight normal -slant roman -underline 0 -overstrike 0")
        self._lbl_unitsLayerHeight.configure(relief="flat")
        self._lbl_unitsLayerHeight.configure(anchor='w')
        self._lbl_unitsLayerHeight.configure(justify='left')
        self._lbl_unitsLayerHeight.configure(takefocus="0")
        self._lbl_unitsLayerHeight.configure(text='''mm''')

        self._lbl_unitsFilamentDia = ttk.Label(self.lf_PrintConfig)
        self._lbl_unitsFilamentDia.place(x=185, y=270, height=22, width=30)
        self._lbl_unitsFilamentDia.configure(background="#d9d9d9")
        self._lbl_unitsFilamentDia.configure(foreground="#000000")
        self._lbl_unitsFilamentDia.configure(font="-family {Segoe UI} -size 10 -weight normal -slant roman -underline 0 -overstrike 0")
        self._lbl_unitsFilamentDia.configure(relief="flat")
        self._lbl_unitsFilamentDia.configure(anchor='w')
        self._lbl_unitsFilamentDia.configure(justify='left')
        self._lbl_unitsFilamentDia.configure(takefocus="0")
        self._lbl_unitsFilamentDia.configure(text='''mm''')

        self._lbl_unitsFirstLayerSpeed = ttk.Label(self.lf_PrintConfig)
        self._lbl_unitsFirstLayerSpeed.place(x=185, y=165, height=22, width=40)
        self._lbl_unitsFirstLayerSpeed.configure(background="#d9d9d9")
        self._lbl_unitsFirstLayerSpeed.configure(foreground="#000000")
        self._lbl_unitsFirstLayerSpeed.configure(font="-family {Segoe UI} -size 10 -weight normal -slant roman -underline 0 -overstrike 0")
        self._lbl_unitsFirstLayerSpeed.configure(relief="flat")
        self._lbl_unitsFirstLayerSpeed.configure(anchor='w')
        self._lbl_unitsFirstLayerSpeed.configure(justify='left')
        self._lbl_unitsFirstLayerSpeed.configure(takefocus="0")
        self._lbl_unitsFirstLayerSpeed.configure(text='''mm/s''')

        self._lbl_unitsTravelSpeed = ttk.Label(self.lf_PrintConfig)
        self._lbl_unitsTravelSpeed.place(x=185, y=190, height=22, width=40)
        self._lbl_unitsTravelSpeed.configure(background="#d9d9d9")
        self._lbl_unitsTravelSpeed.configure(foreground="#000000")
        self._lbl_unitsTravelSpeed.configure(font="-family {Segoe UI} -size 10 -weight normal -slant roman -underline 0 -overstrike 0")
        self._lbl_unitsTravelSpeed.configure(relief="flat")
        self._lbl_unitsTravelSpeed.configure(anchor='w')
        self._lbl_unitsTravelSpeed.configure(justify='left')
        self._lbl_unitsTravelSpeed.configure(takefocus="0")
        self._lbl_unitsTravelSpeed.configure(text='''mm/s''')

        self.scl_CoolingPerc = ttk.Scale(self.lf_PrintConfig, from_=0, to=20)
        self.scl_CoolingPerc.place(x=60, y=53, width=120, height=20)
        self.scl_CoolingPerc.configure(value="10")
        self.scl_CoolingPerc.configure(length="20")
        self.scl_CoolingPerc.configure(takefocus="")
        self.scl_CoolingPerc_var = tk.IntVar()
        self.scl_CoolingPerc.configure(variable = self.scl_CoolingPerc_var)

        self._lbl_Zoffset = ttk.Label(self.lf_PrintConfig)
        self._lbl_Zoffset.place(x=5, y=294, height=22, width=120)
        self._lbl_Zoffset.configure(background="#d9d9d9")
        self._lbl_Zoffset.configure(foreground="#000000")
        self._lbl_Zoffset.configure(font="-family {Segoe UI} -size 10 -weight normal -slant roman -underline 0 -overstrike 0")
        self._lbl_Zoffset.configure(relief="flat")
        self._lbl_Zoffset.configure(anchor='w')
        self._lbl_Zoffset.configure(justify='left')
        self._lbl_Zoffset.configure(takefocus="0")
        self._lbl_Zoffset.configure(text='''Z offset''')

        self._lbl_unitsZoffset = ttk.Label(self.lf_PrintConfig)
        self._lbl_unitsZoffset.place(x=185, y=294, height=22, width=30)
        self._lbl_unitsZoffset.configure(background="#d9d9d9")
        self._lbl_unitsZoffset.configure(foreground="#000000")
        self._lbl_unitsZoffset.configure(font="-family {Segoe UI} -size 10 -weight normal -slant roman -underline 0 -overstrike 0")
        self._lbl_unitsZoffset.configure(relief="flat")
        self._lbl_unitsZoffset.configure(anchor='w')
        self._lbl_unitsZoffset.configure(justify='left')
        self._lbl_unitsZoffset.configure(takefocus="0")
        self._lbl_unitsZoffset.configure(text='''mm''')

        self.ent_Zoffset = ttk.Entry(self.lf_PrintConfig)
        self.ent_Zoffset.place(x=130, y=295, height=20, width=55)
        self.ent_Zoffset.configure(takefocus="")
        # self.ent_Zoffset.configure(cursor="ibeam")
        self.ent_Zoffset_var = tk.StringVar()
        self.ent_Zoffset.configure(textvariable = self.ent_Zoffset_var)

        self.btn_SaveConfig = ttk.Button(top)
        self.btn_SaveConfig.place(x=375, y=341, height=25, width=116)
        self.btn_SaveConfig.configure(takefocus="")
        self.btn_SaveConfig.configure(text='''Save configuration''')

        self.btn_Generate = ttk.Button(top)
        self.btn_Generate.place(x=495, y=341, height=25, width=116)
        self.btn_Generate.configure(takefocus="")
        self.btn_Generate.configure(text='''Generate G-code''')

        self._lbl_Kcalc1 = ttk.Label(top)
        self._lbl_Kcalc1.place(x=10, y=420, height=22, width=250)
        self._lbl_Kcalc1.configure(background="#d9d9d9")
        self._lbl_Kcalc1.configure(foreground="#000000")
        self._lbl_Kcalc1.configure(font="-family {Segoe UI} -size 10 -weight normal -slant roman -underline 0 -overstrike 0")
        self._lbl_Kcalc1.configure(relief="flat")
        self._lbl_Kcalc1.configure(anchor='w')
        self._lbl_Kcalc1.configure(justify='left')
        self._lbl_Kcalc1.configure(takefocus="0")
        self._lbl_Kcalc1.configure(text='''Height with the best quality:              mm''')

        self.ent_Hmeasured = ttk.Entry(top)
        self.ent_Hmeasured.place(x=175, y=420, height=22, width=50)
        self.ent_Hmeasured.configure(takefocus="")
        self.ent_Hmeasured_var = tk.StringVar()
        # self.ent_Hmeasured_var.set("2.5")
        self.ent_Hmeasured.configure(textvariable = self.ent_Hmeasured_var)
        self.ent_Hmeasured.configure(validate = "key", validatecommand = (self.ent_Hmeasured.register(validate), "%P"))

        self.lbl_K = ttk.Label(top)
        self.lbl_K.place(x=375, y=370, height=22, width=250)
        self.lbl_K.configure(background="#d9d9d9")
        self.lbl_K.configure(foreground="#007c00")
        self.lbl_K.configure(font="-family {Segoe UI} -size 10 -weight bold -slant roman -underline 0 -overstrike 0")
        self.lbl_K.configure(relief="flat")
        self.lbl_K.configure(anchor='w')
        self.lbl_K.configure(justify='left')
        self.lbl_K.configure(takefocus="0")
        self.lbl_K.configure(text=''' ''')

        # self.btn_Calc = ttk.Button(top)
        # self.btn_Calc.place(relx=0.385, rely=0.92, height=25, width=110)
        # self.btn_Calc.configure(takefocus="")
        # self.btn_Calc.configure(text='''Calculate K-factor''')

    # Attaching traces and handlers
    def attach(self):
        self.ent_PatternXsize_var.trace_add('write', lambda name, index, mode: self.validate_pattern_X())
        self.ent_BuildVolX_var.trace_add('write', lambda name, index, mode: self.validate_pattern_X())
        self.ent_PatternYsize_var.trace_add('write', lambda name, index, mode: self.validate_pattern_Y())
        self.ent_BuildVolY_var.trace_add('write', lambda name, index, mode: self.validate_pattern_Y())
        self.ent_BuildVolZ_var.trace_add('write', lambda name, index, mode: self.validate_pattern_Z())
        self.ent_StartK_var.trace_add('write', lambda name, index, mode: self.validate_pattern_Z())
        self.ent_StartK_var.trace_add('write', lambda name, index, mode: self.calculate_K())
        self.ent_StopK_var.trace_add('write', lambda name, index, mode: self.validate_pattern_Z())
        self.ent_StepK_var.trace_add('write', lambda name, index, mode: self.validate_pattern_Z())
        self.ent_StepK_var.trace_add('write', lambda name, index, mode: self.calculate_K())
        self.ent_LayersPerK_var.trace_add('write', lambda name, index, mode: self.validate_pattern_Z())
        self.ent_LayersPerK_var.trace_add('write', lambda name, index, mode: self.calculate_K())
        self.ent_LayerHeight_var.trace_add('write', lambda name, index, mode: self.validate_pattern_Z())
        self.ent_LayerHeight_var.trace_add('write', lambda name, index, mode: self.calculate_K())
        self.ent_Hmeasured_var.trace_add('write', lambda name, index, mode: self.calculate_K())
        self.chk_UseAutoleveling.configure(command = self.handle_ABL_chk)
        # self.scl_CoolingPerc.configure(command = self.handle_Cooling_scl)
        self.scl_CoolingPerc_var.trace_add('write', lambda name, index, mode: self.handle_Cooling_scl())
        self.cmb_Kinematics_var.trace_add('write', lambda name, index, mode: self.handle_Kinematics_cmb())
        self.cmb_Firmware_var.trace_add('write', lambda name, index, mode: self.handle_Firmware_cmb())
        self.chk_AAdaptive_var.trace_add('write', lambda name, index, mode: self.calculate_K())
        self.chk_AAdaptive_var.trace_add('write', lambda name, index, mode: self.validate_pattern_Z())
        self.ent_StartA_var.trace_add('write', lambda name, index, mode: self.validate_pattern_Z())
        self.ent_StopA_var.trace_add('write', lambda name, index, mode: self.validate_pattern_Z())
        self.ent_StepA_var.trace_add('write', lambda name, index, mode: self.validate_pattern_Z())

    def register_validator(self):
        for member in vars(self):
            entry = getattr(self, member)
            if isinstance(entry, ttk.Entry) and member.startswith("ent_"):
                entry.configure(validate = "key", validatecommand = (entry.register(validate), "%P"))

    def updateUI(self, config):
        self.ent_SlowSpeed_var.set(str(config.speed_slow))
        self.ent_FastSpeed_var.set(str(config.speed_fast))
        self.ent_StartK_var.set(str(config.k_start))
        self.ent_StopK_var.set(str(config.k_end))
        self.ent_StepK_var.set(str(config.k_step))
        self.ent_LayersPerK_var.set(str(config.layers_per_k))
        self.ent_Zoffset_var.set(str(config.z_offset))

        self.ent_PatternXsize_var.set(str(config.size[0]))
        self.ent_PatternYsize_var.set(str(config.size[1]))

        self.ent_RetractDist_var.set(str(config.retract[0]))
        self.ent_RetractSpeed_var.set(str(config.retract[1]))
        self.ent_BuildVolX_var.set(str(config.bed_size[0]))
        self.ent_BuildVolY_var.set(str(config.bed_size[1]))
        self.ent_BuildVolZ_var.set(str(config.bed_size[2]))
        self.ent_NozzleTemp_var.set(str(config.temperature[0]))
        self.ent_BedTemp_var.set(str(config.temperature[1]))
        self.ent_SpdFr1_var.set(str(config.path_spd_fractions[0]))
        self.ent_SpdFr2_var.set(str(config.path_spd_fractions[1]))
        self.ent_SpdFr3_var.set(str(config.path_spd_fractions[2]))
        self.chk_RetractAtLayerChange_var.set(config.retract_at_layer_change)
        self.chk_TwoPerimeters_var.set(config.double_perimeter)

        self.chk_AAdaptive_var.set(config.a_adaptive)
        self.ent_StartA_var.set(str(config.a_start))
        self.ent_StopA_var.set(str(config.a_end))
        self.ent_StepA_var.set(str(config.a_step))

        self.chk_UseAutoleveling_var.set(config.use_ABL)
        self.cmb_AutolevelingType.configure(values=config.ABL_type_list)
        self.cmb_AutolevelingType.set(config.ABL_type)
        self.cmb_AutolevelingType.configure(state = ("readonly",) if config.use_ABL else ("disabled",))

        self.cmb_Firmware.configure(values=config.firmware_list)
        self.cmb_Firmware.set(config.firmware)
        self.cmb_Kinematics.configure(values=config.kinematics_list)
        self.cmb_Kinematics.set(config.kinematics)
        self.handle_Firmware_cmb()

        self.ent_FilamentDia_var.set(str(config.def_fil_dia))
        self.ent_LineWidth_var.set(str(config.def_line_width))
        self.ent_LayerHeight_var.set(str(config.def_layer))
        self.ent_FirstLayerSpeed_var.set(str(config.def_speed_print))
        self.ent_TravelSpeed_var.set(str(config.def_speed_travel))
        self.lbl_CoolingPerc['text'] = '%s%%' % config.def_cooling
        self.scl_CoolingPerc.set(config.def_cooling/5)

    def pattern_height(self):
        try:
             k_values = abs(float(self.ent_StopK.get())-float(self.ent_StartK.get()))/float(self.ent_StepK.get())
             height = k_values * int(self.ent_LayersPerK.get()) * float(self.ent_LayerHeight.get())
             if self.chk_AAdaptive_var.get() and self.cmb_Firmware.get() == 'Klipper':
                 try:
                     a_step = float(self.ent_StepA.get()) or 200.0
                     a_values = max(1, int(round(abs(float(self.ent_StopA.get())-float(self.ent_StartA.get()))/a_step)) + 1)
                     height = height * a_values
                 except:
                     pass
        except:
            height = 0
        return height

    def calculate_K(self):
        try:
            H = float(self.ent_Hmeasured_var.get())
            Kn = float(self.ent_StartK_var.get())
            L = float(self.ent_LayerHeight_var.get())
            dK = float(self.ent_StepK_var.get())
            Nsk = float(self.ent_LayersPerK_var.get())
            if self.chk_AAdaptive_var.get() and self.cmb_Firmware.get() == 'Klipper':
                try:
                    a_start = float(self.ent_StartA_var.get())
                    a_end = float(self.ent_StopA_var.get())
                    a_step = float(self.ent_StepA_var.get()) or 200.0
                    k_end = float(self.ent_StopK_var.get())
                    num_K = max(1, int(round(abs(k_end - Kn) / dK)) + 1)
                    block_height = L * Nsk
                    block_index = int(H / block_height)
                    k_block_index = block_index % num_K
                    a_block_index = block_index // num_K
                    num_A = max(1, int(round(abs(a_end - a_start) / a_step)) + 1)
                    A_val = a_start + a_block_index * (a_step if a_end >= a_start else -a_step)
                    result = Kn + k_block_index * (dK if k_end >= Kn else -dK)
                    self.lbl_K['text'] = "A = %s, K = %s" % (round(A_val, 0), round(result, 3))
                    self.lbl_K.configure(foreground="#007c00")
                    return result
                except:
                    pass
            result = Kn + int(H/(L*Nsk))*dK
            self.lbl_K['text'] = "Calculated K-factor = %s" % round(result, 3)
            self.lbl_K.configure(foreground="#007c00")
            return result
        except:
            self.lbl_K['text'] = "Error calculating K-factor"
            self.lbl_K.configure(foreground="#ff0000")

    def validate_pattern_X(self):
        # size = float(self.ent_PatternXsize.get()) if self.ent_PatternXsize.get() else 0.0
        # vol = float(self.ent_BuildVolX.get()) if self.ent_BuildVolX.get() else 0.0
        if not self.cmb_Kinematics.get()=='Delta':
            try:
            #     result = size < vol - 20
                result = float(self.ent_PatternXsize.get()) < float(self.ent_BuildVolX.get()) - 20
            except:
                result = False
        else:
            try:
                diag = sqrt(float(self.ent_PatternXsize.get())**2 + float(self.ent_PatternYsize.get())**2)
                result =  diag < float(self.ent_BuildVolX.get()) - 25
            except:
                result = False
        self.ent_PatternXsize.configure(foreground = "#000000" if result else "#ff0000")
        return result

    def validate_pattern_Y(self):
        # size = float(self.ent_PatternYsize.get()) if self.ent_PatternYsize.get() else 0.0
        # vol = float(self.ent_BuildVolY.get()) if self.ent_BuildVolY.get() else 0.0
        if not self.cmb_Kinematics.get()=='Delta':
            try:
            #     result = size < vol - 20
                result = float(self.ent_PatternYsize.get()) < float(self.ent_BuildVolY.get()) - 20
            except:
                result = False
        else:
            result = self.validate_pattern_X()
        self.ent_PatternYsize.configure(foreground = "#000000" if result else "#ff0000")
        return result

    def validate_pattern_Z(self):
        # vol = float(self.ent_BuildVolZ.get()) if self.ent_BuildVolZ.get() else 0.0
        try:
        #     result = self.pattern_height() < vol - 10
            result = self.pattern_height() < float(self.ent_BuildVolZ.get()) - 10
        except:
            result = False
        self.lbl_PatternZsize['text'] = "x %.2f mm" % self.pattern_height()
        self.lbl_PatternZsize.configure(foreground="#000000" if result else "#ff0000")
        return result

    def handle_ABL_chk(self):
        self.cmb_AutolevelingType.configure(state = ("readonly",) if self.chk_UseAutoleveling_var.get() else ("disabled",))

    def handle_Cooling_scl(self):
        perc = self.scl_CoolingPerc_var.get()*5
        self.lbl_CoolingPerc['text'] = '%s%%' % perc

    def handle_Firmware_cmb(self):
        is_klipper = self.cmb_Firmware.get() == 'Klipper'
        self.chk_AAdaptive.configure(state="normal" if is_klipper else "disabled")
        for w in [self._lbl_AFrom, self.ent_StartA, self._lbl_ATo, self.ent_StopA, self._lbl_ABy, self.ent_StepA]:
            w.configure(state="normal" if is_klipper else "disabled")
        if not is_klipper:
            self.chk_AAdaptive_var.set(False)
        self.validate_pattern_Z()
        self.calculate_K()

    def handle_Kinematics_cmb(self):
        if self.cmb_Kinematics.get() == 'Delta':
            self.ent_BuildVolY.configure(state = "disabled")
            self.ent_BuildVolY_var.set(self.ent_BuildVolX_var.get())
        else:
            self.ent_BuildVolY.configure(state = "!disabled")
        self.revalidate_all()

    def revalidate_all(self):
        self.validate_pattern_X()
        self.validate_pattern_Y()
        self.validate_pattern_Z()
        self.handle_ABL_chk()
        self.handle_Cooling_scl()
        self.handle_Firmware_cmb()

# root = tk.Tk()
# top = Toplevel(root)
# for member in top.__dict__.keys():
#     if isinstance(getattr(top, member), ttk.Entry):
#         print(member)

if __name__ == '__main__':
    vp_start_gui()
